### ISSUE TITLE
ValueDecision::doMake returns null if NonBlockingRuleErrorInterface is thrown

### ISSUE THREAD

**Issue by egor-dev** [loyaltycorp/easy-decision#1]
`ValueDecision::doMake` returns `null` if `NonBlockingRuleErrorInterface` is thrown (`$this->input` remains unassigned). We expect to get the same value, that was passed in input.

**Comment by natepage** [comment]
Hey Egor, thank you for your PR it has been fixed in https://github.com/loyaltycorp/easy-monorepo/pull/93.
